<?php

namespace fascli\MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * commissionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class commissionsRepository extends EntityRepository
{
	public function toutcommissions()
{
 
    $qb = $this->createQueryBuilder('c');
   $qb ->addOrderBy('c.id', "DESC");
   return $qb->getQuery()
            ->getResult();
}

public function comMois(){
    $now = new \DateTime();
    $nowd = '1';
    $nowm = $now->format('m');
    $nowy = $now->format('Y');
    $qb = $this->createQueryBuilder('c');
   $qb ->where('DAY(c.debutperiode) >= :nowd')
    ->setParameter('nowd', $nowd)
    ->andwhere('MONTH(c.debutperiode) = :nowm')
    ->setParameter('nowm', $nowm)
   ->andwhere('YEAR(c.debutperiode) = :nowy')
    ->setParameter('nowy', $nowy);
   return $qb->getQuery()
            ->getResult();
}

}
