<?php

namespace fascli\MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * commissionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class depensesRepository extends EntityRepository
{
	public function toutdepenses()
{
 
    $qb = $this->createQueryBuilder('d');
   $qb ->addOrderBy('d.id', "DESC");
   return $qb->getQuery()
            ->getResult();
}

public function depensesMois(){
    $now = new \DateTime();
    $nowd = '1';
    $nowm = $now->format('m');
    $nowy = $now->format('Y');
    $qb = $this->createQueryBuilder('c');
   $qb ->where('DAY(c.datdepense) >= :nowd')
    ->setParameter('nowd', $nowd)
    ->andwhere('MONTH(c.datdepense) = :nowm')
    ->setParameter('nowm', $nowm)
   ->andwhere('YEAR(c.datdepense) = :nowy')
    ->setParameter('nowy', $nowy);
   return $qb->getQuery()
            ->getResult();
}

}
