<?php

namespace fascli\MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * nouvellesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class nouvellesRepository extends EntityRepository
{
	public function toutnouvelles()
{
 
    $qb = $this->createQueryBuilder('n');
   $qb ->addOrderBy('n.id', "DESC");
   return $qb->getQuery()
            ->getResult();
}
}
