security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_WU:    [ROLE_USER]
        ROLE_BDC:   [ROLE_USER, ROLE_WU]
        ROLE_TAUXBDC:   [ROLE_USER, ROLE_WU, ROLE_BDC]
        ROLE_BACKOFFICE: [ROLE_USER, ROLE_WU, ROLE_BDC]
        ROLE_ADMIN: [ROLE_USER, ROLE_WU, ROLE_BDC, ROLE_BACKOFFICE]
        ROLE_RAF:   [ROLE_USER, ROLE_WU, ROLE_BDC, ROLE_BACKOFFICE, ROLE_ADMIN]
        ROLE_DG: []

    providers:
        fos_userbundle:
             id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                csrf_provider: form.csrf_provider
            logout:
                path:   fos_user_security_logout
                target: fos_user_security_login
            anonymous:    true
        login_firewall:
            pattern:   ^/login$
            anonymous: ~

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/$, role: ROLE_USER }
        - { path: ^/*, role: ROLE_USER }
        - { path: ^/app$, role: ROLE_USER }
        - { path: ^/taux/*$, role: ROLE_TAUXBDC }
        - { path: ^/taux$, role: ROLE_TAUXBDC }