<?php

namespace fascli\BdcBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * gbpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class gbpRepository extends EntityRepository
{
	public function getLignesForGbps($clientId)
    {
        
        $qb = $this->createQueryBuilder('a')
                   ->select('a')
                   ->where('a.operationsbdc_id = :client_id')
                   ->setParameter('client_id', $clientId)
                   ->addOrderBy('a.id',"ASC");
           
        return $qb->getQuery()
                  ->getResult();
    }
}
