<?php

namespace fascli\BdcBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * operationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class operationsbdcRepository extends EntityRepository
{
}
