<?php

namespace fascli\BdcBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * tauxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tauxRepository extends EntityRepository
{
	private function convertirTaux($taux)
	{
        return floatval($taux);		
	}

	private function trouveEntityTaux($indice){
		$ent = $this->findOneById($indice);
       return $ent;
    }

    public function trouveTaux($indice,$ope)
	{
		$taux = '0';
		$qb = $this->trouveEntityTaux($indice);
       if($ope=='EA'){$taux=$qb->getEA();}
       if($ope=='EV'){$taux=$qb->getEV();}
       if($ope=='DA'){$taux=$qb->getDA();}
       if($ope=='DV'){$taux=$qb->getDV();}
       if($ope=='GA'){$taux=$qb->getGA();}
       if($ope=='GV'){$taux=$qb->getGV();}
       if($ope=='SA'){$taux=$qb->getSA();}
       if($ope=='SV'){$taux=$qb->getSV();}
       return $this->convertirTaux($taux);
    }

    public function trouveType($ope)
	{
		$type = '0';
       if($ope=='EA'){$type='ACHAT';}
       if($ope=='EV'){$type='VENTE';}
       if($ope=='DA'){$type='ACHAT';}
       if($ope=='DV'){$type='VENTE';}
       if($ope=='GA'){$type='ACHAT';}
       if($ope=='GV'){$type='VENTE';}
       if($ope=='SA'){$type='ACHAT';}
       if($ope=='SV'){$type='VENTE';}
       return $type;
    }

    public function trouveDevise($ope)
	{
		$devise ='';
       if($ope=='EA'){$devise ='EURO';}
       if($ope=='EV'){$devise ='EURO';}
       if($ope=='DA'){$devise ='DOLLAR';}
       if($ope=='DV'){$devise ='DOLLAR';}
       if($ope=='GA'){$devise ='GBP';}
       if($ope=='GV'){$devise ='GBP';}
       if($ope=='SA'){$devise ='SUISSE';}
       if($ope=='SV'){$devise ='SUISSE';}
       return $devise;
    }
}
